### ISSUE TITLE
Abuse of Conduct

### ISSUE THREAD

**Issue by firery-feign** [Funwithtony/GameDev22-Antonio#2]
Has mean and abusive content on index page

**Comment by Funwithtony** [comment]
David you are not tolerated around here pls leave and go fin somewhere else to be mean

**Comment by firery-feign** [comment]
no

**Comment by Funwithtony** [comment]
![download](https://user-images.githubusercontent.com/113381141/199570451-8bc52f9f-8714-4c68-95d5-c9713ebf107e.jpg)
